const images = {
  // main_logo: require("../Images/mainLogo.jpg"),
  // main_logo_e: require("../Images/mainLogoE.png"),
  // main_logo_transparent: require("../Images/mainLogoTransparent.png"),
  // main_bg_front: require("../Images/main_logo/bg_login.png"),
  ic_not_found: require("../Images/signal_not_found.jpg"),
  ic_mountain: require("../Images/ic_mountain.png"),
  ic_mountain_transparent: require("../Images/ic_mountain_transparent.png"),
  ic_information: require("../Images/ic_information.png"),

  ic_search_img: require("../Images/ic_search.png"),
  ic_not_found_new: require("../Images/not_found.png"),
  
  ic_about_profil: require("../Images/profile_browsing.png"),
  ic_about_profil1: require("../Images/profile_details.png"),
  ic_about_profil2: require("../Images/profile_choice.png"),
  
  backArrow: require("../Images/backArrow.png"),
  backArrowSignUpTen: require("../Images/backArrowGrey.png"),
  backBlackArrow: require("../Images/backBlackArrow.png"),
  blueCameraIcon: require("../Images/blueCameraIcon.png"),
  close_signin_15: require("../Images/close_signin_15.png"),
  cloude: require("../Images/cloude.png"),
  deleteIcon: require("../Images/deleteIcon.png"),
  downArrowIcon: require("../Images/downArrowIcon.png"),
  favorite_fab: require("../Images/favorite_fab.png"),
  cameraIcon: require("../Images/ic_camera.png"),
  backArrowSignUpNine: require("../Images/ic_Left_arrow_black_su09.png"),
  mapPinIcon: require("../Images/ic_map_pin.png"),
  mapPinWhite: require("../Images/ic_map_pin.png"),
  mapPinRed: require("../Images/map.png"),
  nearByIcon: require("../Images/ic_nearby_inactive.png"),
  nearByActiveIcon: require("../Images/ic_nearby.png"),
  phone: require("../Images/ic_phone.png"),
  slideUpArrowIcon: require("../Images/ic_slide_up_arrow.png"),
  location: require("../Images/location.png"),
  roundedcross: require("../Images/roundedcross.png"),
  settingsIcon: require("../Images/settingIcon.png"),
  starEmpty1: require("../Images/starEmpty1.png"),
  starFilled1: require("../Images/starFilled1.png"),
  starHalf1: require("../Images/starHalf1.png"),
  filter: require("../Images/ic_filter.png"),
  No_image_found: require("../Images/No_image.png"),
  Destinationstype: require("../Images/Destinationstype.png"),
  transporation: require("../Images/transporation.png"),
  nature: require("../Images/ic_nature.png"),
};

export default images;
